### ISSUE TITLE
Jquery & sammy libs in vendor folder ?

### ISSUE THREAD

**Issue by Hypee** [zappajs/zappajs#2]
Shouldn't we provide 'jquery-1.7.2.min.js' and 'sammy-0.7.1.min.js' in the /vendor folder ?
Or did I miss something ?

**Comment by shimaore** [comment]
They get automatically added when you do `cake vendor` or `cake setup` after checking out the project.

If you download the npm package they are already included.

**Comment by Hypee** [comment]
Ok, thanks for the response !

So maybe should we include that in the readme, or is that so obvious that it isn't needed ?

About NPM, what is your plan to take over the current zappajs package ?

**Comment by shimaore** [comment]
What's really needed is a proper `scripts` section in `package.json`. I'd expect most people will use the npm package except if they are writing code for zappajs itself, in which case the Cakefile is pretty explicit.

For npm the package is now called [`zappajs`](http://search.npmjs.org/#/zappajs) instead of `zappa`.

**Comment by Hypee** [comment]
Damn, you're going fast ;)
