### ISSUE TITLE
Zappajs 0.4, restoring "partial" functionality

### ISSUE THREAD

**Issue by Hypee** [zappajs/zappajs#23]
The following code is working in ZappaJS 0.3.9 but not in ZappaJS 0.4.0 due to the migration from Express 2 to Express 3 where "partial" functionality has been removed.

``` coffeescript
#
# Installed : 
# npm install zappa@0.3.9 (working) or npm install zappa@0.4.0 (non working)
# npm install eco
#

require('zappajs') ->

    #
    # CoffeeCup views
    #
    @view 'header': ->
        head ->
            "I'm the header"

    @view 'footer': ->
        p ->
            "I'm the footer"

    @view 'page': ->
        partial 'header'
        p ->
            text "I'm the body"
        partial 'footer'

    #
    # Eco views
    #
    @view 'header.eco': 
        '''
        <head>
            I'm the header
        </head>
        '''

    @view 'footer.eco': 
        '''
        <p>
            I'm the footer
        </p>
        '''

    @view 'page.eco': 
        '''
        <%- @partial 'header.eco' %>
        <p>I'm the body</p>
        <%- @partial 'footer.eco' %>
        '''

    #
    # Routes
    #

    # CoffeeCup page
    @get '/': ->
        @render 'page', {layout:false}

    # Eco page
    @get '/eco': ->
        @render 'page.eco', {layout:false}
```

 An Express 3 middleware project is restoring the "partial" functionality (https://github.com/publicclass/express-partials) but it's currently limited to EJS templates.

**Comment by shimaore** [comment]
The `partial` feature in `coffeecup` is added in `coffeecup.adapter.express` as a `hardcode` feature.
There's no reference to `partial` in `eco` so it must be a reference to `@partial` of Express 2.x.

**Comment by shimaore** [comment]
Please give v0.4.1 a test; download it with `npm install zappajs@0.4.1`. (I set the `latest` at 0.3.9 because #24 breaks all the basic examples.)
I added `partial` as a member of `locals` for now; but it should be accessible as `@partial` in CoffeeCup or ECO. I need to add some tests for it; if I can make it a member of the options set directly this should speed things up for CoffeeCup; I'll look into this later.

**Comment by Hypee** [comment]
Thanks for this fast update !
That's not working yet on my side but seems it's very close.

In zappa.coffee, If I replace 

``` coffeescript
opts.locals.partial = (name) ->
  partial name, opts
```

by

``` coffeescript
opts.partial = (name) ->
  partial name, opts
```

@partial in views works, but asynchronously (I guess), so the view is rendered before/without the return of partials.

I've already resolved this kind of problem with helpers, allowing them to execute asynchronous code, but I let you check before going further.

**Comment by shimaore** [comment]
Slept over this... if the goal of moving Zappa to Express 3 is to make things faster (and not just "let's get the latest version"), I think re-introducing `partial` (or `layout`) just goes against the tide, since we're rendering multiple times, and therefor making things way slower.

As I understand it now, the goal (in Express 3) of pushing these down towards the template engines (e.g. the addition of [includes](https://github.com/visionmedia/jade#a13) in Jade, which essentially are partials) is to compile the entire template (`layout` and `partial`s included) once, and re-use it in a single function call.
(Quick benchmarks using `layout` in Zappa 0.4 showed the double-rendering putting performance down 30%, compared to a single rendering.)

So if we're going to (re)introduce partials anywhere, it should be in CoffeeCup, Eco, etc., not in Zappa; so that the template engine's compiler can build the code once. Assuming Express 3 will gain traction, we should expect some of the engines to eventually do that.

Now this brings us back to the issue of how to provide the content of inline views to the template engines. `consolidate` and `jade` assume `fs.readFile` or `fs.readFileSync` are the proper tools to access view text. I opened visionmedia/jade#682 on this topic.

**Comment by Hypee** [comment]
Well, on a very selfish point of view, I don't really care, I've already done a helper that emulates "partials" behavior and manages the async problem. I'm also having an internal cache, so rendering time is not too much a concern.

But I'm a little bit sad to see a functionality being dropped from Zappa, providing a template engine agnostic "include" mechanism sounds pretty cool.

**Comment by shimaore** [comment]
Well it's not being selfish if you share with us ;)

About your second point: I'm not set against keeping partials or layout. But these features were both provided by Express in 2.x (so there was nothing specific Zappa had to do to get them), Express dropped them in 3.x, so now I'm trying to figure out whether it's best for Zappa to re-implement them (and what that means), or whether the solution should come from the template engines. From a performance point of view it seems they should come from the template engines; so if we can get good alternatives from there it will be great: we'll get performance _and_ ease-of-coding. In the other case then yes, let's try to emulate these the best we can, and let the Zappa coder choose the performance vs ease-of-coding balance. We'll have a `@use` option for that, or something. :)

Overall this means that the Express "ecosystem" (including Zappa at this point) is still trying to figure things out for Express 3.x. So anything we do in the 0.4 branch of Zappa for now is going to be experimental as well. Which is also why I'm keeping the `latest` label in the `npm` repository on the 0.3.x release, so that we can keep experimenting here without breaking people's existing Zappa code -- until we have a viable alternative in 0.4, at some later point.

So let's keep playing with `partial` a little bit more here, sorry my last comment sounded like that was the end of it all. I'm just thinking aloud (I also got scared by the benchmarks, I have to say).

**Comment by Hypee** [comment]
Thanks for your friendly response.

You are absolutely right about the fact that layout & partials were provided by Express, I started using Node.js with Zappa, so sometimes I forget where functionalities are coming from.

We probably want to keep Zappa as small and maintainable as possible, so maybe the best solution is to try to use a middleware for the partial/layout functionality (for engines that dont provide it -yet-), allowing existing code to easily migrate to Zappa 0.4.

Regards.

**Comment by shimaore** [comment]
@Hypee Agreed about using middleware for this, I re-used your reference to `express-partials` and opened publicclass/express-partials#2

**Comment by shimaore** [comment]
304f8b8325d494c5836539ebdfa6ef56a12a2443 adds back support for partials and layout using `express-partials`.
(Note: test cases are currently broken but I submitted a patch to express-partials for that. Single-instance zappa should work fine with express-partials 0.0.4.)

The documentation still needs to be updated, leaving this issue opened for documentation purposes.

**Comment by scien** [comment]
all my templates worked after upgrading to zappajs 0.4.5, adding zappajs-partials 0.0.6, and adding @use 'partials'

express-partials patch was closed a while back.  tests for partials appear to be passing (though getting four :not reached"s for server broadcasts). my one note would be to to change "coffeekup" to "coffeecup" in the comments here. https://github.com/shimaore/express-partials/blob/master/index.js .  newcomers would be very confused.

**Comment by shimaore** [comment]
Ideally I'd like to not have to maintain `zappajs-partials` and rather use plain `express-partials`, but the Zappa tests don't go through with plain `express-partials` (hence publicclass/express-partials#4 , but that issue went off and the 'multiple Express instances' patch didn't get applied there).

I'm not sure I documented this, but you can do `@use partials: {'html':'jade'}` to register extensions (in this case `html` files are processed through `jade`). And `@use 'partials'` might return the `express-partials` object -- although, would a `@partials` object be useful in the Zappa application context?

**Comment by shimaore** [comment]
`@use partials: ...` is documented.
Still no sign of getting concurrent instances running in `expressjs-partials`; I updated `zappajs-partials` to follow fixes in `expressjs-partials`.
