### ISSUE TITLE
Where's the Dynamic Helpers?

### ISSUE THREAD

**Issue by Radagaisus** [zappajs/zappajs#29]
`@app.dynamicHelpers` - nada e nada.

**Comment by shimaore** [comment]
Apparently this was removed from Express 3.x. If you are using Zappa 0.4.x or the master trunk then this won't be available anymore. (Zappa 0.3.x still depends on Express 2.x, and should be the default release installed via `npm`.)
This issue is similar to visionmedia/express#1067 which references https://github.com/visionmedia/express/wiki/Migrating-from-2.x-to-3.x which itself says to use middleware + `res.locals` instead of `dynamicHelpers`.

If you have an example we can use for Zappa documentation of how to migrate to Zappa 0.4.x I'd be glad to include it in the distribution.

**Comment by Radagaisus** [comment]
Sorry :-)

``` coffee
myMiddleware = (req, res, next) ->
  res.locals.csrf = if req.session then req.session.csrf else ''
```
