### ISSUE TITLE
@json and @jsonp

### ISSUE THREAD

**Issue by Radagaisus** [zappajs/zappajs#47]
Hi,

Just like we have `@send` I think we should have `@json`.

There was a recent commit to express that [separated json and jsonp requests](https://github.com/visionmedia/express/commit/a6caa267bd1948f014885d6fe8463cd7d1b7af77). I used a small middleware for this so far, but it will be nice to support this as well.

**Comment by shimaore** [comment]
`@json` is in [the routes](https://github.com/zappajs/zappajs/blob/master/src/zappa.coffee#L408).

I'm all for explicit semantics, so `@jsonp` sounds interesting (although Istill use `@send` for `@json` in my code, bad habit). The only question is whether it is present in a released (npm) version of Express so that we can point the `dependecies` to it?

**Comment by Radagaisus** [comment]
`@json` isn't documented on zappajs.com.

Looking at the releases jsonp is in 3.0.0rc4.

**Comment by shimaore** [comment]
For the latest docs please use http://zappajs.github.com/zappajs/docs/reference

**Comment by Radagaisus** [comment]
I'll try to add tests soon =/

How can we test `@jsonp`?

**Comment by datashaman** [comment]
Pull Request: https://github.com/zappajs/zappajs/pull/86

**Comment by datashaman** [comment]
This can be closed.
