### ISSUE TITLE
Session trouble

### ISSUE THREAD

**Issue by tbleckert** [zappajs/zappajs#50]
Hi!

I'm having a hard time working with sessions. Before I found zappajs I used just expressjs. Express.js have an example of how to work with sessions to create basic authentication:

https://github.com/visionmedia/express/blob/master/examples/auth/app.js

I tried to do that in zappa with no luck. I use it like this:

```
@use 'bodyParser',  'cookieParser': {secret: 'shhhh, very secret'}, 'session': {secret: 'shhhh, very secret'}
```

But I never seem to have access to the session. I'm sure that I'm just doing it wrong, sorry for my lack of skills. It would be awesome to have an example likte that one.

**Comment by Radagaisus** [comment]
Zappa IS express, it just wraps it in a neat CoffeeScript DSL.

``` coffee
@use @express.cookieParser 'MySuperSecretSecret'
@use @express.session()
```

Is the proper form.

**Comment by shimaore** [comment]
> I never seem to have access to the session.

It's accessible using `@session` when you are in a routing block; to plagiarize the express example you mentioned:

```
@post '/login': ->
  authenticate @body.username, @body.password, (err,user) =>
    if user
      @session.regenerate =>
        @session.user = user
```

The one thing to notice is that you need to use the "fat arrows" in CoffeeScript to have the top (route-block) context being propagated when you enter new functions.

Alternatively you can just save the context or the request object; this is similar to what you would do in plain Javascript:

```
@post '/login': ->
  ctx = @
  authenticate @body.username, @body.password, (err,user) ->
    if user
      ctx.session.regenerate ->
        ctx.session.user = user
```

Please provide more details if your problem is different -- I'm rather second-guessing here. :)

**Comment by shimaore** [comment]
Closing for now, please re-open if needed.
