### ISSUE TITLE
Zappajs with Express 3.x

### ISSUE THREAD

**Issue by Hypee** [zappajs/zappajs#7]
I've spent some time today, playing with Zappajs and Express 3 and I've published my first results :
https://github.com/Hypee/zappajs/tree/express_3

The management of template engines has totally changed in Express 3, for now I've activated CoffeeKup, Eco and Jade engines, but we have to find a way to make that more dynamic.

Layouts and Partials are gone in Express 3, so tests using them are failing.
Socket.io isn't working, I didn't take a look yet.

**Comment by shimaore** [comment]
Tasks here:
- test
- figure out how to map the ZappaJS API to Express 3.0 for things that fail
- re-introduce zappa.apapter (or document a migration path)
- benchmark (to make sure we're doing at least as well as with Express 2)

**Comment by shimaore** [comment]
I had a long look at Express 3.0, and essentially the monkey patching will go even deeper this time around.

Express moved from a model where it used the `.compile(text)` method of a template module, to a model where it uses a `.renderFile(path)` method. With Express 2.0 Zappa only had to patch the functions in Express that loaded the template text; in 3.0, if an Express-compatible template engine decides to follow only the Express model and provides only `.renderFile()`, there's no way we can use it in `@render`.

Of course CoffeeCup isn't ready for the new `renderFile` Express convention, and neither are most of the other template engines -- hence [consolidate.js](https://github.com/visionmedia/consolidate.js). From afar it looks like Express trying to shoehorn the existing template conventions into its new model.

In any case: we'll have to assume in Zappa that template engines continue to export a .compile() function, and monkey-patch Express 3.0 around that (although it would probably make sense to only monkey-patch when trying to render `@view`, and let Express do its thing otherwise).

**Comment by shimaore** [comment]
I worked on an extensive rewrite, trying to do minimal changes (modifying the `lookup` function mostly) but it's essentially impossible in Express 3 -- the View object and the list of engines are encapsulated and not accessible from outside express, which prevents you from altering `lookup` in a meaningful way.
[edit] That's independent of the issues I mentioned in the previous update regarding `compile` vs `renderFile`. [/edit]
So the solution will be to provide an alternate version of `render`, which I still have to code.

**Comment by Hypee** [comment]
Just to be sure, did you take a look at the code I've done ? 
From what I remember, I've replaced the existing monkey patching and @render was working (not 100% sure).

**Comment by shimaore** [comment]
@Hypee -- I wasn't sure your code supported `set 'view engine'` or automatically loading the template module based on the extension (`use_engine` was hardcoded with three template modules), so I tried to reintroduce these, using your code as a starting point. (Failed attempt [here](https://gist.github.com/2878394).)
Also I'd like to keep `zappa.adapter` if we can.

**Comment by shimaore** [comment]
Some notes as I've now spent a fair amount of time trying to code this:
- Express3 has no notion of `layout`, so in order to keep the same API in Zappa we'd have to code this back.
- But that would not even be sufficient: includes in `eco` and `jade` read the included files (such as layout documents) directly off the disk. In order to get this to work with `@view` we would have to replace `fs.readFileSync` and all the related functions. Or store the `@view` documents on the disk.
- Express3 has no `register`, would need to be added back in.

My current changes trying to address some of these issues are in 87a17059246d2551e633f1f2a134530704858ed4
[As a side note, I ended up patching the private Express instance (instead of patching the module), this gives more flexibility on the other hand (no need for Zappa instance `id`).]

I'm going to assume for now that we want to keep the Express model as the reference for what we do in Zappa. That model obviously changed a lot with Express3.

As one can see in the commit, trying to emulate the old view model will lead to a significant increase in the size of the zappa code (and as I mentioned above, we know this will not work in all situations). Here are the options which look somewhat valid at this point with regards to the `@view` situation:
- keep `@view` in Zappa and store the documents on the disk (at runtime) to make Express3 happy;
- get rid of `@view` and force the developer to store their view/layout documents as separate files.

Regarding the concept of layout, this would become a Zappa particularism since it got dropped from Express3, with the explicit goal of forcing the templating engines to support includes. CoffeeCup doesn't seem to have includes (yet?).

`partial` also got dropped.

**Comment by shimaore** [comment]
Maybe this is a better approach:
- Keep `@view` and document the fact that (if kept inline) they can't be used from `app.render`, only from `@render`. In the new `@render` we use `require(engine).compile()` for inline views and fall back to Express3 for on-disk views. We do not try to monkey-patch Express3.
- (compatible with the one above) Add a `export_views` option to Zappa which would indicate a subdirectory under `views/` where to store the content of inline views at runtime. (This avoids an issue with using a dynamic `context.id`, different for each Zappa run, making re-using inline, stored views, inaccessible from Express3 views. This also allows environments where you might not be able to write at runtime, e.g. embedded, to still work with Zappa.)

**Comment by shimaore** [comment]
After more research, it looks like the best option might be to monkey-patch the new cache in express. I'm trying that route now.
